trigger:
- main

pool:
  name: my-agent

variables:
- group: devsecops-secrets

stages:

# -------------------------
# 🔍 SONAR (DOCKER - NO EXTENSION)
# -------------------------
- stage: Sonar
  jobs:
  - job: SonarScan
    steps:
    - checkout: self

    - script: |
        docker run --rm \
        -e SONAR_TOKEN=$(SONAR_TOKEN) \
        -v $(pwd):/usr/src \
        sonarsource/sonar-scanner-cli \
        -Dsonar.projectKey=nehal-wandhare_gamehub \
        -Dsonar.organization=nehal-wandhare \
        -Dsonar.host.url=https://sonarcloud.io
      displayName: SonarCloud Scan

# -------------------------
# 🔐 SNYK SCAN
# -------------------------
- stage: Snyk
  jobs:
  - job: SnykScan
    steps:
    - checkout: self

    - script: |
        echo "Scanning frontend..."
        cd frontend
        npm install
        npx snyk auth $(SNYK_TOKEN)
        npx snyk test --severity-threshold=high > ../snyk-frontend.txt

        echo "Scanning backend..."
        cd ../backend
        npm install
        npx snyk test --severity-threshold=high > ../snyk-backend.txt
      displayName: Run Snyk Scan

    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: snyk-frontend.txt
        artifactName: snyk-frontend

    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: snyk-backend.txt
        artifactName: snyk-backend

# -------------------------
# 🐳 BUILD + TRIVY
# -------------------------
- stage: BuildAndScan
  jobs:
  - job: Build
    steps:
    - checkout: self

    - script: |
        docker-compose build
      displayName: Build Docker

    - script: |
        docker run --rm \
        -v /var/run/docker.sock:/var/run/docker.sock \
        aquasec/trivy image frontend:latest > trivy-report.txt
      displayName: Trivy Scan

    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: trivy-report.txt
        artifactName: trivy-report

# -------------------------
# 🚀 DEPLOY
# -------------------------
- stage: Deploy
  dependsOn: BuildAndScan
  jobs:
  - job: DeployJob
    steps:
    - script: |
        docker-compose down || true
        docker-compose up -d
      displayName: Deploy App